spring:
  application:
    name: eureka-of-store-ha
---
spring:
  profiles: peer1                                 # 指定profile=peer1
server:
  port: 8761
eureka:
#  instance:
#    hostname: peer1ip                               # 指定当profile=peer1时，主机名是peer1
  client:
    serviceUrl:
      defaultZone: http://peer2ip:8762/eureka/      # 将自己注册到peer2这个Eureka上面去

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
#  instance:
#    hostname: peer2ip
  client:
    serviceUrl:
      defaultZone: http://peer1ip:8761/eureka/